# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('aborted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=3, verbose_name='Field size')),
                ('min_length', models.IntegerField(default=3, verbose_name='Line length')),
                ('allow_horizontal', models.BooleanField(default=True)),
                ('allow_vertical', models.BooleanField(default=True)),
                ('allow_diagonal', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'verbose_name': 'Move',
                'ordering': ('created',),
                'verbose_name_plural': 'Moves',
            },
        ),
    ]
