# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 22:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_line',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='game',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
