# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_diagonal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='allow_horizontal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='allow_vertical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_length',
            field=models.IntegerField(default=3, verbose_name='Line length'),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=3, verbose_name='Field size'),
        ),
    ]
