# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160809_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
